apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: "messenger-db"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "messenger"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_PASS: "password123"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secret, key: DB_PASS } }
            - name: POSTGRES_DB
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_NAME } }
            - name: PGUSER
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_USER } }
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: messenger-db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ldotexe/messenger-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: APP_PORT
              value: "8000"
            - name: PORT
              value: "8000"
            
            - name: POSTGRES_HOST
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_HOST } }
            - name: POSTGRES_PORT
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_PORT } }
            - name: POSTGRES_DB
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_NAME } }
            - name: POSTGRES_USER
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_USER } }
            
            - name: POSTGRES_PW
              valueFrom: { secretKeyRef: { name: app-secret, key: DB_PASS } }

            - name: DB_HOST
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_HOST } }
            - name: DB_PORT
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_PORT } }
            - name: DB_NAME
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_NAME } }
            - name: DB_USER
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_USER } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secret, key: DB_PASS } }

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ldotexe/messenger-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ldotexe/messenger-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 80