# ИСПРАВЛЕНИЕ: Используем более свежий Python 3.11
FROM python:3.11-slim

# Устанавливаем SSH-клиент и sshpass
RUN apt-get update && apt-get install -y openssh-client sshpass

# ИСПРАВЛЕНИЕ: Устанавливаем Python-модули и коллекции
RUN pip install --upgrade pip && \
    pip install ansible docker requests && \
    ansible-galaxy collection install community.docker

WORKDIR /ansible

CMD ["tail", "-f", "/dev/null"]