FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    openssh-client \
    sshpass \
    git \
    nodejs \
    npm

RUN pip install --upgrade pip && \
    pip install ansible docker requests && \
    ansible-galaxy collection install community.docker

WORKDIR /ansible

CMD ["tail", "-f", "/dev/null"]
